version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: install protoc
          command: |
            mkdir protobuf
            curl -sSL https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip > protobuf/protoc.zip
            unzip -d protobuf protobuf/protoc.zip
            export PATH=$PATH:$(pwd)/protobuf/bin
            protoc --version
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: test & cleanup
          command: |
            npm install
            npm run prepare

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - build
      - test:
          requires:
            - build